package com.tqs_assignment.airquality.selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.assertThat;

public class AirQualityCoordinatesTestPage {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost:8080/");
        driver.manage().window().setSize(new Dimension(1296, 741));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void whenRightCityFormat() throws InterruptedException {
        driver.findElement(By.id("place")).click();
        driver.findElement(By.id("place")).sendKeys("Aveiro,Portugal");
        driver.findElement(By.id("searchButton")).click();
        driver.findElement(By.id("dominant")).click();
        assertThat(driver.findElement(By.id("dominant")).getText(), containsString("Dominant pollutant: "));
        driver.findElement(By.id("aqi")).click();
        assertThat(driver.findElement(By.id("aqi")).getText(), containsString("Air Quality: "));
        driver.findElement(By.id("category")).click();
        assertThat(driver.findElement(By.id("category")).getText(), containsString("Description: "));
        Thread.sleep(5000);
        driver.findElement(By.id("latitude")).click();
        assertThat(driver.findElement(By.id("latitude")).getText(), containsString("Latitude: "));
    }

    @Test
    public void whenInexistingCity_thenUndefined() {
        driver.findElement(By.id("place")).click();
        driver.findElement(By.id("place")).sendKeys("Not,ExistingPlaces");
        driver.findElement(By.id("searchButton")).click();
        driver.findElement(By.id("dominant")).click();
        assertThat(driver.findElement(By.id("dominant")).getText(), containsString("undefined"));
        assertThat(driver.findElement(By.id("aqi")).getText(), containsString("undefined"));
        assertThat(driver.findElement(By.id("category")).getText(), containsString("undefined"));
        //  driver.findElement(By.id("latitude")).click();
        // assertThat(driver.findElement(By.id("latitude")).getText(), containsString("0"));
    }

    @Test
    public void whenEmptyCity_thenUndefined() {
        driver.findElement(By.id("searchButton")).click();
        driver.findElement(By.id("dominant")).click();
        assertThat(driver.findElement(By.id("dominant")).getText(), containsString("undefined"));
        assertThat(driver.findElement(By.id("aqi")).getText(), containsString("undefined"));
        assertThat(driver.findElement(By.id("category")).getText(), containsString("undefined"));
    }
}
