package com.tqs_assignment.airquality.selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.assertThat;

public class HourlyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
    driver.get("http://localhost:8080/hourly");
    driver.manage().window().setSize(new Dimension(1296, 741));
    WebDriverWait wait = new WebDriverWait(driver, 20);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void WhenCorrectPlaceAndHours_thenData() {
    driver.findElement(By.id("place")).click();
    driver.findElement(By.id("place")).sendKeys("Aveiro,Portugal");
    driver.findElement(By.id("hours")).click();
    {
      WebElement element = driver.findElement(By.id("hours"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("hours")).sendKeys("3");
    driver.findElement(By.id("searchButton")).click();
    assertThat(driver.findElement(By.cssSelector(".list-group:nth-child(2) > .list-group-item:nth-child(1)")).getText(), containsString("Pollutant"));
    assertThat(driver.findElement(By.cssSelector(".list-group:nth-child(3) > .list-group-item:nth-child(1)")).getText(), containsString("Pollutant"));
    assertThat(driver.findElement(By.cssSelector(".list-group:nth-child(4) > .list-group-item:nth-child(1)")).getText(), containsString("Pollutant"));
  }
}
